#
#
#

version: '3'

services:

    php:
        image: registry-vpc.cn-hongkong.aliyuncs.com/io-lzz/php
        
        restart: always

        environment:
            - TZ="Asia/Shanghai"
               
        ports:
            - 9000:9000


    nginx:
        image: registry-vpc.cn-hongkong.aliyuncs.com/io-lzz/nginx-php
        restart: always

        environment:
            - TZ="Asia/Shanghai"
       
        #volumes:
            #- logs/:/usr/local/nginx/logs
            #- logs:/var/log/nginx
            
        ports:
            - 80:80
             
#volumes:
#    logs:

