#! /bin/bash
#
# ossfs      Automount Aliyun OSS Bucket in the specified direcotry.
#
# chkconfig: 2345 90 10
# description: Activates/Deactivates ossfs configured to start at boot time.

ossfs my373 /oss/my373 -ourl=http://oss-cn-hangzhou.aliyuncs.com -oallow_other
