version: '3.6'

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    # hostname: 'node3.lzz.io'
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://node3.lzz.io:20080'

    ports:
      #- '80:80'
      #- '443:443'
      #- '22:22'
      - '20080:20080'
    volumes:
      # mkdir -p ./config ./logs ./data
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
      #- gitlab-config:/etc/gitlab
      #- gitlab-logs:/var/log/gitlab
      #- gitlab-data:/var/opt/gitlab

    deploy:
      replicas: 1
      labels: [APP=gitlab]
      placement:
        constraints: [node.hostname == node3]

#volumes:
#  gitlab-config:
#  gitlab-logs:
#  gitlab-data:

