#
#
#

version: '3'

services:

    php:
        image: registry-vpc.cn-hongkong.aliyuncs.com/io-lzz/php
        
        restart: always

        environment:
            - TZ="Asia/Shanghai"
               
        ports:
            - 80:80
