version: '3'

services:

    zookeeper1:
        image: zookeeper
        container_name: zookeeper1
        restart: always
        hostname: zookeeper1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        volumes:
             - zookeeper1-data:/data
             - zookeeper1-log:/datalog
        networks:
            mynet:

        deploy:
            replicas: 1
            labels: [APP=zookeeper1]
            placement:
                constraints: [node.hostname == node1]

    zookeeper2:
        image: zookeeper
        container_name: zookeeper2
        restart: always
        hostname: zookeeper2
        # ports:
        #     - 2181:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        volumes:
             - zookeeper2-data:/data
             - zookeeper2-log:/datalog
        networks:
            mynet:

        deploy:
            replicas: 1
            labels: [APP=zookeeper2]
            placement:
                constraints: [node.hostname == node2]

    zookeeper3:
        image: zookeeper
        container_name: zookeeper3
        restart: always
        hostname: zookeeper3
        # ports:
        #     - 2181:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
        volumes:
             - zookeeper3-data:/data
             - zookeeper3-log:/datalog
        networks:
            mynet:

        deploy:
            replicas: 1
            labels: [APP=zookeeper3]
            placement:
                constraints: [node.hostname == node3]


volumes:
    zookeeper1-data:
    zookeeper1-log:
    zookeeper2-data:
    zookeeper2-log:
    zookeeper3-data:
    zookeeper3-log:


## for docker stack
networks:
    mynet:
        external: true

