version: "2"

services:
  nexus:
    image: sonatype/nexus
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
      - /etc/localtime:/etc/localtime:ro #时区问题
    ports:
      - "8081:8081"
  
volumes:
  nexus-data: {}