version: '3.6'

services:
    redis:
        image: redis
        hostname: "{{.Service.Name}}-{{.Task.Slot}}"
        ports:
            - 6379:6379
        environment:
            - TZ=CST-8

        command: redis-server /data/redis.conf

        volumes:
            - ./redis.conf:/data/redis.conf
            - redis-data:/data

        # networks:
        #     mynet:

        deploy:
            replicas: 1
            labels: [APP=redis]
            placement:
                constraints: [node.hostname == node1]


    mongo:
        image: mongo:4.0-rc
        hostname: "{{.Service.Name}}-{{.Task.Slot}}"
        ports:
            - 27017:27017
        environment:
            TZ: CST-8
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: q1w2e3r4

        volumes:
            - mongo-data:/data/db
            - mongo-conf:/data/configdb

        deploy:
            labels: [APP=mongo]
            placement:
                constraints: [node.hostname == node2]

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: q1w2e3r4

    rabbitmq:
        image: rabbitmq:3-management
        hostname: "{{.Service.Name}}-{{.Task.Slot}}"
        ports:
            - 5671:5671
            - 5672:5672
            - 15672:15672
        environment:
            TZ: CST-8
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: q1w2e3r4

        volumes:
            - rabbitmq-data:/var/lib/rabbitmq

        deploy:
            labels: [APP=rabbitmq]
            placement:
                constraints: [node.hostname == node3]

networks:
    default:
        # attachable: true
        name: mynet
        external: true


volumes:
    redis-data:

    mongo-data:
    mongo-conf:

    rabbitmq-data:


