# Run docker stack deploy -c stack.yml mysql (or docker-compose -f stack.yml up), 
# wait for it to initialize completely,
# and visit http://swarm-ip:8080, http://localhost:8080, or http://host-ip:8080 (as appropriate).

# Use root/example as user/password credentials
version: '3.6'

services:

    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        command: "--default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

    adminer:
        image: adminer
        ports:
            - 8080:8080
